language: python
python:
  #- 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  # Coverage runs the py27 test suite
  - TOXENV=coverage
  - TOXENV=flake8
  - TOXENV=pylint
matrix:
  exclude:
    - env: TOXENV=flake8
    - env: TOXENV=pylint
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=pylint
install: |
  pip install coveralls tox
  cp -f ./tests/.hgrc $HOME
script: |
  tox
after_success: |
  if [ "${TOXENV}" = "coverage" ]; then
    coveralls
  fi

#vim:set et sw=2 ts=2:
