language: python
sudo: false
cache:
  directories:
    - $DEPS
env:
  global:
    - DEPS=$HOME/deps
    - PATH=$DEPS/bin:$PATH
matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=pylint
    - python: 2.7
      env: TOXENV=coverage
    - python: 3.5
      env: TOXENV=coverage
    - python: 3.4
      env: TOXENV=pytest
    - python: 3.3
      env: TOXENV=pytest
    - python: 3.2
      env: TOXENV=pytest
install: |
  cp -f ./tests/.hgrc $HOME
  cp -f ./tests/pakit.yaml $HOME/.pakit.yaml
  pip install coveralls tox pyyaml

  if [ "$TOXENV" = "pytest" -o "$TOXENV" = "coverage" ]; then
    if [ -e "$DEPS/bin/7z" ]; then
      echo "Using CACHE at $DEPS."
    else
      echo "Running travis installation."
      bash ./tests/install.sh
    fi
  fi
script: |
  tox
after_success: |
  if [ "${TOXENV}" = "coverage" ]; then
    coveralls
  fi

#vim:set et sw=2 ts=2:
