language: python
python:
  #- 2.6
  - 2.7
  #- 3.4
  #- 3.5

before_script:
  pip install coveralls mock pytest pytest-mock PyYAML

script:
  coverage run --source wok -m py.test

after_success:
  coveralls

#vim:set et sw=2 ts=2:
