language: python
python:
  #- 2.6
  - 2.7
  #- 3.4
  #- 3.5
env:
  # Coverage runs the py27 test suite
  - TOXENV=coverage
  - TOXENV=flake8
  - TOXENV=pylint
install:
  pip install tox
script:
  tox
after_success: |
  if [ "${TOXENV}" = "coverage" ]; then
    coveralls
  fi

#vim:set et sw=2 ts=2:
