language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
env:
  # 'coverage' runs the regular test suite & reports to coveralls
  - TOXENV=coverage
  - TOXENV=flake8
  - TOXENV=pylint
  - TOXENV=pytest
matrix:
  exclude:
    - env: TOXENV=coverage
    - env: TOXENV=flake8
    - env: TOXENV=pylint
    - env: TOXENV=pytest
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=pylint
    - python: 2.7
      env: TOXENV=coverage
    - python: 3.2
      env: TOXENV=coverage
    - python: 3.3
      env: TOXENV=pytest
    - python: 3.4
      env: TOXENV=pytest
    - python: 3.5
      env: TOXENV=pytest
install: |
  sudo apt-get install unrar p7zip-full
  pip install coveralls tox
  cp -f ./tests/.hgrc $HOME
script: |
  tox
after_success: |
  if [ "${TOXENV}" = "coverage" ]; then
    coveralls
  fi

#vim:set et sw=2 ts=2:
